# Numpy array creation,Functions and Attributes

In [20]:
import numpy as np
import sys

## Functions

### array() 

In [21]:
tuple1 = (1,2,3,4,5)
list1 = [2,1,34,5]
arr1 = np.array(arr) # array() will create an array from a python list or tupple
arr2 = np.array(list1)

print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]]
[ 2  1 34  5]


- compairing memory usage of python list and numpy arrays

In [22]:
list2 = [1,2,3,4,5,6,7]
arr = np.array(list2)

print(sys.getsizeof(list2))
print(arr.nbytes)

120
56


### logspace()

In [23]:
arr = np.logspace(1,3,5,dtype = int) # will create a logrithmic scale array like evenly spaced power values
                                     #and default number of points is 50  default base value is 10
arr


array([  10,   31,  100,  316, 1000])

### zeors()

In [24]:
arr = np.zeros([4,4]) # will create an array full of zeros -> 
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### linspace()

In [25]:
arr = np.linspace(20,30,6) # will create evenly spaced values on a specific intervel -> (start,stop,numberofvalues)
arr

array([20., 22., 24., 26., 28., 30.])

### arange()

In [26]:
arr = np.arange(1,11) # will create an array of evenly spaced values uses step size ->(start,stop,step)
                      # it will exclude the stop value the array stop before the stop value
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### ones()

In [27]:
arr = np.ones([2,3],dtype=int) #will create an array full of ones
arr

array([[1, 1, 1],
       [1, 1, 1]])

### full()

In [28]:
arr = np.full([2,3],7) # will create an array of any values -> (number/diamension,value)
arr

array([[7, 7, 7],
       [7, 7, 7]])

### random.rand()

In [29]:
arr = np.random.rand(2) # will creat an array of random float values by default between 0 and 1 cannot change the
                          # default value directly always generate floats cannot change data type
arr

array([0.96734277, 0.52128112])

### random.randn()

In [30]:
arr = np.random.randn(2) # exactly like rand but values mostly arround 0 or close to 0 the numbers can be negative or positive
arr

array([-0.72378158,  0.56092037])

### random.randint()

In [31]:
arr = np.random.randint(1,10,5) # it will generate random integers between the given start and stop -> 
                                # (start,stop,dimention/numberof values)
arr

array([4, 9, 5, 9, 5])

### reshape()

In [32]:
arr = np.arange(1,11).reshape(2,5) # reshape can change the dimention of an array

arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### concatenate(())

In [33]:
arr1 = np.arange(1,11).reshape(2,5)
arr2 = np.arange(11,21).reshape(2,5)

arr3 = np.concatenate((arr1,arr2)) # can join 2 or more arrays to one array with in an existing axis

arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

### stack(())

In [34]:
arr1 = np.arange(1,13).reshape(2,2,3)
arr2 = np.arange(13,25).reshape(2,2,3)

arr3 = np.stack((arr1,arr2)) # it wil join 2 or more arrays but add a new axis(changes diamension)

arr3

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]],


       [[[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]]])

In [35]:
arr = np.random.randint(1,50,20)
mask = arr %2!=0

odd = arr[mask] # this is called masking used for filtering the boolean values 
even = arr[~mask]
mask

array([ True,  True, False, False,  True, False, False, False, False,
        True,  True, False,  True, False, False, False, False,  True,
       False,  True])

### resize()

In [36]:
arr = np.arange(1,20)

arr.resize(6,6) # used to reshape an array if the size is large it fill fill automatically with default value 0

arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]])

### ravel()

In [37]:
arr = np.zeros([2,2,3])
convert = arr.ravel() # used to convert a multi diamensional array to 1d array if any changes applyied it will affect the og array
convert[0] = 100

print(convert)
print(arr)


[100.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
[[[100.   0.   0.]
  [  0.   0.   0.]]

 [[  0.   0.   0.]
  [  0.   0.   0.]]]


### flatten()

In [38]:
arr = np.array([[1,2,3,4],[1,2,3,4]])
copy = arr.flatten() # used to convert a multidiamensional array to 1d array | always return a copy so og array didint affect by the changes

copy[0] = 100
print(arr)
print(copy)

[[1 2 3 4]
 [1 2 3 4]]
[100   2   3   4   1   2   3   4]


### take()

In [39]:
arr = np.array([[1,2,3,4],
               [3,2,33,5]])
ind = [1,2,5,6]
t = np.take(arr,ind) # is a build in function to perform indexing and slicing

t

array([ 2,  3,  2, 33])

### nditer() 

In [40]:
arr = np.array([[12,32,42,53,23],
                [1,2,43,54,21]])

for x in np.nditer(arr): # used for loop through an array items
    print(x)

12
32
42
53
23
1
2
43
54
21


### .view() .copy()

In [41]:
arr = np.array([1,2,3,4,5])

arr1 = arr.view() # to perform shallow copy it will ponit the copy to original memmory if copy changes original also changes

arr1[0]=100

print(arr1)
print(arr)



[100   2   3   4   5]
[100   2   3   4   5]


In [42]:
arr2 = arr.copy()
# to perform deep copy returns a new independend array and it will not affect the original array
arr2[0]=200
arr2

array([200,   2,   3,   4,   5])

### transpose()

In [43]:
arr = np.array([[1,2],
                [3,4]])
print(arr.transpose()) # used for swaping rows and columns

[[1 3]
 [2 4]]


### hstack() --- vstack()

In [44]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

vstack = np.vstack((a,b)) # to join arrays in vertically
hstack = np.hstack((a,b)) # to join array in horizontally

vstack

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### repeat() --- tile()

In [45]:
arr = np.array([1,2,3,4,5])

print(np.repeat(arr,3)) # will repeat elements only 

print(np.tile(arr,2)) # will repeat the entire array

[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]
[1 2 3 4 5 1 2 3 4 5]


## Type Casting and Atributes

### astype()

In [46]:
arr = np.arange(1,11).reshape(2,5)
arr1 = arr.astype(str) # can change from a data type to another
arr1

array([['1', '2', '3', '4', '5'],
       ['6', '7', '8', '9', '10']], dtype='<U21')

In [47]:
arr = np.array([1,2,3,4],dtype = str) # in this way also we can type cast
arr

array(['1', '2', '3', '4'], dtype='<U1')

### dtype

In [48]:
arr = np.array([22,12,32,44])
arr.dtype # to check data types of an array

dtype('int64')

### shape

In [49]:
arr = np.arange(1,11).reshape(2,5)
arr.shape # will check how many rows and columns are present in an array

(2, 5)

### size

In [50]:
arr = np.arange(1,11)
arr.size # will check how many elemnts are present in an array

10

### ndim

In [51]:
arr = np.zeros([2,2,3])
arr.ndim # can check the array diamension

3

### diag()

In [52]:
arr = np.random.randint(1,50,[4,4])
extract = np.diag(arr) # will extract diagonal values from matrix
print(arr)
print(extract)

[[46 47 38 17]
 [20 25 35 22]
 [43  5 47 35]
 [27 23 29  3]]
[46 25 47  3]


# questions

In [53]:
arr = np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
arr = np.arange(30).reshape(6,5)
print(arr)
n =arr[0:,3]
n

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


array([ 3,  8, 13, 18, 23, 28])

In [55]:
arr = np.zeros([8,8],dtype = int)
arr[1::2,::2]=1
arr[::2,1::2] =1

print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [56]:
arr = np.arange(1,21)
c =np.split(arr,4)
c

[array([1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15]),
 array([16, 17, 18, 19, 20])]

In [57]:
arr = np.ones([10,10])
arr[1:-1,1:-1]=0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [58]:
arr = np.random.randint(1,10,9).reshape(3,3)
arr1 = arr.flatten()
sort = np.sort(arr1)[::-1]

sort

array([9, 9, 8, 7, 6, 5, 4, 3, 2])

In [59]:
arr = np.arange(1,7).reshape(2,3)
arr1 = np.arange(8,14).reshape(2,3)

stack = np.hstack((arr,arr1))
stack

array([[ 1,  2,  3,  8,  9, 10],
       [ 4,  5,  6, 11, 12, 13]])

In [60]:
arr = np.arange(1,11)

s = arr.sum()
m = arr.mean()
sd = arr.std()
md = np.median(arr)
print(m)

5.5


### np.unique(array,return_counts=True)
- used for finding frequency numbers in an array

In [61]:
arr = np.array([1,2,2,3,2,3,5,4,3,4,5,4,3,2,3,4])
value,count = np.unique(arr, return_counts = True) # for finding frequency number of an array 
print(value)
print(count)

[1 2 3 4 5]
[1 4 5 4 2]


### np.eye()
- is used to create identity matix

In [62]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### broadcasting
- automatically expands a smaller array to match the shape of a larger array durng a mathematical operations without making a copy

In [63]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([2,3,4,5])
print(arr1+arr2)

[3 5 7 9]


In [71]:
arr = np.eye(4)

arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

- replacing negative values with 0

In [75]:
arr = np.array([1,2,-1,-4,4,-4,8,4,-3])
arr[arr<0] = 0
arr

array([1, 2, 0, 0, 4, 0, 8, 4, 0])

In [76]:
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [77]:
arr = np.random.randint(0,10,[3,3])
arr

array([[4, 6, 0],
       [6, 5, 4],
       [8, 3, 4]])

In [80]:
arr = np.array([1,2,3,2,3,2,5,4,3,4,5])

c = np.unique(arr)

c

array([1, 2, 3, 4, 5])

### np.dot()
- used for multiplying the entier matix value

In [83]:
arr1 = np.array([1,2,3])
arr2 = np.array([2,3,4])

b = np.dot(arr1,arr2)
b

np.int64(20)

In [94]:
arr = np.arange(1,21)

extract = arr[np.where(arr%2==0)]
extract

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [101]:
arr = np.array([1,2,5,3,4,3,2,5,3,5,4,5,5])

ar = np.bincount(arr).argmax() # used for find the most frequent number

print(ar)

5
