# Numpy array creation,Functions and Attributes

In [ ]:
import numpy as np
import sys

## Functions

### array() 

In [ ]:
tuple1 = (1,2,3,4,5)
list1 = [2,1,34,5]
arr1 = np.array(arr) # array() will create an array from a python list or tupple
arr2 = np.array(list1)

print(arr1)
print(arr2)

- compairing memory usage of python list and numpy arrays

In [ ]:
list2 = [1,2,3,4,5,6,7]
arr = np.array(list2)

print(sys.getsizeof(list2))
print(arr.nbytes)

### logspace()

In [ ]:
arr = np.logspace(1,3,5,dtype = int) # will create a logrithmic scale array like evenly spaced power values
                                     #and default number of points is 50  default base value is 10
arr


### zeors()

In [ ]:
arr = np.zeros([4,4]) # will create an array full of zeros -> 
arr

### linspace()

In [ ]:
arr = np.linspace(20,30,6) # will create evenly spaced values on a specific intervel -> (start,stop,numberofvalues)
arr

### arange()

In [ ]:
arr = np.arange(1,11) # will create an array of evenly spaced values uses step size ->(start,stop,step)
                      # it will exclude the stop value the array stop before the stop value
arr

### ones()

In [ ]:
arr = np.ones([2,3],dtype=int) #will create an array full of ones
arr

### full()

In [ ]:
arr = np.full([2,3],7) # will create an array of any values -> (number/diamension,value)
arr

### random.rand()

In [ ]:
arr = np.random.rand(2) # will creat an array of random float values by default between 0 and 1 cannot change the
                          # default value directly always generate floats cannot change data type
arr

### random.randn()

In [ ]:
arr = np.random.randn(2) # exactly like rand but values mostly arround 0 or close to 0 the numbers can be negative or positive
arr

### random.randint()

In [ ]:
arr = np.random.randint(1,10,5) # it will generate random integers between the given start and stop -> 
                                # (start,stop,dimention/numberof values)
arr

### reshape()

In [ ]:
arr = np.arange(1,11).reshape(2,5) # reshape can change the dimention of an array

arr

### concatenate(())

In [ ]:
arr1 = np.arange(1,11).reshape(2,5)
arr2 = np.arange(11,21).reshape(2,5)

arr3 = np.concatenate((arr1,arr2)) # can join 2 or more arrays to one array with in an existing axis

arr3

### stack(())

In [ ]:
arr1 = np.arange(1,13).reshape(2,2,3)
arr2 = np.arange(13,25).reshape(2,2,3)

arr3 = np.stack((arr1,arr2)) # it wil join 2 or more arrays but add a new axis(changes diamension)

arr3

In [ ]:
arr = np.random.randint(1,50,20)
mask = arr %2!=0

odd = arr[mask] # this is called masking used for filtering the boolean values 
even = arr[~mask]
mask

### resize()

In [ ]:
arr = np.arange(1,20)

arr.resize(6,6) # used to reshape an array if the size is large it fill fill automatically with default value 0

arr

### ravel()

In [ ]:
arr = np.zeros([2,2,3])
convert = arr.ravel() # used to convert a multi diamensional array to 1d array if any changes applyied it will affect the og array
convert[0] = 100

print(convert)
print(arr)


### flatten()

In [ ]:
arr = np.array([[1,2,3,4],[1,2,3,4]])
copy = arr.flatten() # used to convert a multidiamensional array to 1d array | always return a copy so og array didint affect by the changes

copy[0] = 100
print(arr)
print(copy)

### take()

In [ ]:
arr = np.array([[1,2,3,4],
               [3,2,33,5]])
ind = [1,2,5,6]
t = np.take(arr,ind) # is a build in function to perform indexing and slicing

t

### nditer() 

In [ ]:
arr = np.array([[12,32,42,53,23],
                [1,2,43,54,21]])

for x in np.nditer(arr): # used for loop through an array items
    print(x)

### .view() .copy()

In [ ]:
arr = np.array([1,2,3,4,5])

arr1 = arr.view() # to perform shallow copy it will ponit the copy to original memmory if copy changes original also changes

arr1[0]=100

print(arr1)
print(arr)



In [ ]:
arr2 = arr.copy()
# to perform deep copy returns a new independend array and it will not affect the original array
arr2[0]=200
arr2

### transpose()

In [ ]:
arr = np.array([[1,2],
                [3,4]])
print(arr.transpose()) # used for swaping rows and columns

### hstack() --- vstack()

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

vstack = np.vstack((a,b)) # to join arrays in vertically
hstack = np.hstack((a,b)) # to join array in horizontally

vstack

### repeat() --- tile()

In [ ]:
arr = np.array([1,2,3,4,5])

print(np.repeat(arr,3)) # will repeat elements only 

print(np.tile(arr,2)) # will repeat the entire array

## Type Casting and Atributes

### astype()

In [ ]:
arr = np.arange(1,11).reshape(2,5)
arr1 = arr.astype(str) # can change from a data type to another
arr1

In [ ]:
arr = np.array([1,2,3,4],dtype = str) # in this way also we can type cast
arr

### dtype

In [ ]:
arr = np.array([22,12,32,44])
arr.dtype # to check data types of an array

### shape

In [ ]:
arr = np.arange(1,11).reshape(2,5)
arr.shape # will check how many rows and columns are present in an array

### size

In [ ]:
arr = np.arange(1,11)
arr.size # will check how many elemnts are present in an array

### ndim

In [ ]:
arr = np.zeros([2,2,3])
arr.ndim # can check the array diamension

### diag()

In [ ]:
arr = np.random.randint(1,50,[4,4])
extract = np.diag(arr) # will extract diagonal values from matrix
print(arr)
print(extract)

# questions

In [248]:
arr = np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [241]:
arr = np.arange(30).reshape(6,5)
print(arr)
n =arr[0:,3]
n

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


array([ 3,  8, 13, 18, 23, 28])

In [250]:
arr = np.zeros([8,8],dtype = int)
arr[1::2,::2]=1
arr[::2,1::2] =1

print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [252]:
arr = np.arange(1,21)
c =np.split(arr,4)
c

[array([1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15]),
 array([16, 17, 18, 19, 20])]

In [254]:
arr = np.ones([10,10])
arr[1:-1,1:-1]=0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [260]:
arr = np.random.randint(1,10,9).reshape(3,3)
arr1 = arr.flatten()
sort = np.sort(arr1)[::-1]

sort

array([9, 7, 6, 5, 4, 3, 2, 1, 1])

In [264]:
arr = np.arange(1,7).reshape(2,3)
arr1 = np.arange(8,14).reshape(2,3)

stack = np.hstack((arr,arr1))
stack

array([[ 1,  2,  3,  8,  9, 10],
       [ 4,  5,  6, 11, 12, 13]])

In [271]:
arr = np.arange(1,11)

s = arr.sum()
m = arr.mean()
sd = arr.std()
md = np.median(arr)
print(m)

5.5
