# Numpy review Questions

In [1]:
import numpy as np

arr = np.arange(10,51)

arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [2]:
arr = np.arange(9).reshape(3,3)

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
arr = np.eye(4)

arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [4]:
arr = np.arange(0,11)
arr[arr%2!=0] = -1

arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

In [6]:
arr = np.arange(9).reshape(3,3)

b = np.transpose(arr)

b

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])